=== elenakout/PHP-Ge3-2020-21/assets/files/report.dtd
<!ELEMENT report (semester, student*)>
<!ELEMENT semester (#PCDATA)>
<!ELEMENT student (name, lastname, completed, average)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT completed (#PCDATA)>
<!ELEMENT average (#PCDATA)>
<!ATTLIST student id CDATA #REQUIRED>

=== elenakout/PHP-Ge3-2020-21/assets/files/report.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE report SYSTEM "report.dtd">
<report>
  <semester>1</semester>
  <student id="1">
    <name>elena</name>
    <lastname>kout</lastname>
    <completed>10</completed>
    <average>6.5</average>
  </student>
  <student id="2">
    <name>thanos</name>
    <lastname>kouim</lastname>
    <completed>5</completed>
    <average>10</average>
  </student>
  <student id="3">
    <name>stasis</name>
    <lastname>akouim</lastname>
    <completed>5</completed>
    <average>8</average>
  </student>
  <student id="4">
    <name>elisabet</name>
    <lastname>pegia</lastname>
    <completed>8</completed>
    <average>5</average>
  </student>
</report>

=== elenakout/PHP-Ge3-2020-21/assets/files/report_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE report SYSTEM "report.dtd">
<report>
  <semester>2</semester>
  <student id="12">
    <name>Κασσιανή</name>
    <lastname>Βαριμπόμπη</lastname>
    <completed>2</completed>
    <average>7.0</average>
  </student>
  <student id="9">
    <name>Μαρία</name>
    <lastname>Θεωδωροπούλου</lastname>
    <completed>1</completed>
    <average>7.0</average>
  </student>
  <student id="18">
    <name>Ορφέας</name>
    <lastname>Οικονομίδης</lastname>
    <completed>4</completed>
    <average>8.0</average>
  </student>
  <student id="19">
    <name>Νεφέλη</name>
    <lastname>Οικονομοπούλου</lastname>
    <completed>3</completed>
    <average>6.0</average>
  </student>
  <student id="20">
    <name>Εύα</name>
    <lastname>Ράφτη</lastname>
    <completed>5</completed>
    <average>6.6</average>
  </student>
</report>

=== elenakout/PHP-Ge3-2020-21/assets/files/report_5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE report SYSTEM "report.dtd">
<report>
  <semester>2</semester>
  <student id="65">
    <name>Ευλαμπία</name>
    <lastname>Κοκκίνου</lastname>
    <completed>4</completed>
  </student>
  <student id="37">
    <name>Έλενα</name>
    <lastname>Κουτούση</lastname>
    <completed>5</completed>
  </student>
  <student id="68">
    <name>Νεφέλη</name>
    <lastname>Παπαδοπούλου</lastname>
    <completed>3</completed>
  </student>
  <student id="6">
    <name>Ζωή</name>
    <lastname>Παπαστάμου</lastname>
    <completed>2</completed>
  </student>
</report>
